language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash # until yarn is
  - export PATH=$HOME/.yarn/bin:$PATH                 # pre-installed

script:
  - node bin/ci.js

matrix:
  include:
    - sudo: false
      env: TEST_TYPE=lint_and_test_unit
      node_js: 6.11.1

    # test creating a new project with the LTS version
    - sudo: false
      env: TEST_TYPE=test_create_project_npm
      node_js: 6.11.1

    # test creating a new project with the latest version
    - sudo: false
      env: TEST_TYPE=test_create_project_npm
      node_js: 8.4.0

    - sudo: false
      env: TEST_TYPE=test_create_project_yarn
      node_js: 6.11.1

    # Test with Chrome available
    - dist: trusty
      addons:
        chrome: stable
      sudo: false
      env:
        - TEST_TYPE=integration_test
        - BROWSER=Chrome
      node_js: 6.11.1

cache:
  directories:
    - node_modules

before_deploy:
  - npm prune
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: paulo@ragonha.me
  api_key:
    secure: uwtKe6c+QPSOi7QLCGmVw5cIxl4XDAhaxVWKmRT/GA5CUALjY7ZY1i9Kn6mjcIcvW9HxATU51BASSfq3otWoSJnJB+J3E0kMHJTDW5JMYbQoeu0jRz6ny/FnQoNGvtd3GEAxBkRLCmE0bUzA+1hY+ZxTF/k+zcn2jWcdZk6VGsE=
  on:
    tags: true
    repo: saguijs/sagui
